import grocery1 from '../images/grocery/01.jpg';
import grocery2 from '../images/grocery/02.jpg';
import grocery3 from '../images/grocery/03.jpg';
import grocery4 from '../images/grocery/04.jpg';
import grocery5 from '../images/grocery/05.jpg';
import grocery6 from '../images/grocery/06.jpg';
import grocery7 from '../images/grocery/07.jpg';
import grocery8 from '../images/grocery/08.jpg';
import grocery9 from '../images/grocery/09.jpg';
import grocery10 from '../images/grocery/10.jpg';

export const cards = [
    {
      id: 'card1',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card2',
      discount: 15,
      image: grocery2,
      title: "Gerber Oatmeal Cereal for Babies",
      description: "Iron-fortified cereal to support brain development. Smooth texture for easy swallowing.",
      additionalInfo: "Non-GMO, single grain, and pediatrician recommended. Use within 30 days of opening.",
      kg: 0.5,
      price: 28,
      value: 33,
      count: 1,
      category: "Meats & Seafood",
      life: new Date(),
      tags: ["baby", "oatmeal", "gerber"],
      brand: "Gerber",
      productType: "Limited Edition",
      reviewCount: 8,
      ratingStars: { five: 6, four: 1, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card3',
      discount: 10,
      image: grocery3,
      title: "Heinz Banana Multigrain Cereal",
      description: "Delicious banana flavor with multigrains to help your baby grow strong and healthy.",
      additionalInfo: "Rich in Vitamin D, calcium and iron. Store in airtight container.",
      kg: 0.75,
      price: 32,
      value: 36,
      count: 1,
      category: "Breads & Bakery",
      life: new Date(),
      tags: ["heinz", "banana", "baby"],
      brand: "Heinz",
      productType: "Pre-order",
      reviewCount: 12,
      ratingStars: { five: 7, four: 2, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card4',
      discount: 20,
      image: grocery4,
      title: "Nestle Cerelac Rice & Milk",
      description: "Perfect starter cereal for babies beginning solid food journey. Made with rice and milk.",
      additionalInfo: "Recommended for 6+ months. Easy to digest and free from added preservatives.",
      kg: 1,
      price: 34,
      value: 42,
      count: 1,
      category: "Chips & Snacks",
      life: new Date(),
      tags: ["rice", "cerelac", "starter"],
      brand: "Nestle",
      productType: "Custom",
      reviewCount: 14,
      ratingStars: { five: 8, four: 3, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card5',
      discount: 5,
      image: grocery5,
      title: "Beech-Nut Multigrain Baby Cereal",
      description: "Organic multigrain cereal with no artificial ingredients. Simple and clean nutrition.",
      additionalInfo: "Certified organic. Gluten-free. Perfect for babies 6 months+.",
      kg: 0.6,
      price: 30,
      value: 32,
      count: 1,
      category: "Medical Healthcare",
      life: new Date(),
      tags: ["organic", "multigrain", "beech-nut"],
      brand: "Beech-Nut",
      productType: "Exclusive",
      reviewCount: 7,
      ratingStars: { five: 4, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card6',
      discount: 30,
      image: grocery6,
      title: "Happy Baby Organic Oats & Quinoa Cereal",
      description: "Blend of oats and quinoa for your baby’s healthy development. USDA organic certified.",
      additionalInfo: "Rich in iron and fiber. No artificial flavors or colors.",
      kg: 0.65,
      price: 26,
      value: 37,
      count: 1,
      category: "Frozen Foods",
      life: new Date(),
      tags: ["happybaby", "quinoa", "organic"],
      brand: "Happy Baby",
      productType: "Special Release",
      reviewCount: 9,
      ratingStars: { five: 6, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card7',
      discount: 18,
      image: grocery7,
      title: "Similac Go & Grow Toddler Food",
      description: "Toddler formula with DHA and iron to support growth and brain development.",
      additionalInfo: "Contains milk and soy. Use only as directed.",
      kg: 0.9,
      price: 38,
      value: 46,
      count: 1,
      category: "Grocery & Staples",
      life: new Date(),
      tags: ["similac", "toddler", "formula"],
      brand: "Similac",
      productType: "Limited Edition",
      reviewCount: 11,
      ratingStars: { five: 7, four: 2, three: 1, two: 1, one: 0 }
    },
    {
      id: 'card8',
      discount: 12,
      image: grocery8,
      title: "Earth’s Best Whole Grain Cereal",
      description: "Whole grain cereal made with organic ingredients. Easy on your baby’s tummy.",
      additionalInfo: "Non-GMO and iron-fortified. For babies 6 months+.",
      kg: 0.7,
      price: 29,
      value: 33,
      count: 1,
      category: "Vitamin Foods",
      life: new Date(),
      tags: ["earthsbest", "wholegrain", "organic"],
      brand: "Earth’s Best",
      productType: "Pre-order",
      reviewCount: 6,
      ratingStars: { five: 3, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card9',
      discount: 22,
      image: grocery9,
      title: "Nestum Infant Cereal Wheat & Honey",
      description: "Infant cereal with wheat and honey. A delicious, iron-rich food for babies.",
      additionalInfo: "Contains gluten and milk. Suitable for 8+ months.",
      kg: 1,
      price: 33,
      value: 42,
      count: 1,
      category: "Diet Foods",
      life: new Date(),
      tags: ["nestum", "wheat", "honey"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 13,
      ratingStars: { five: 6, four: 4, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card10',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Healthy Foods",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Cereal snack",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card11',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Vitamin Items",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Exclusive",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card12',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card13',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card14',
      discount: 15,
      image: grocery2,
      title: "Gerber Oatmeal Cereal for Babies",
      description: "Iron-fortified cereal to support brain development. Smooth texture for easy swallowing.",
      additionalInfo: "Non-GMO, single grain, and pediatrician recommended. Use within 30 days of opening.",
      kg: 0.5,
      price: 28,
      value: 33,
      count: 1,
      category: "Meats & Seafood",
      life: new Date(),
      tags: ["baby", "oatmeal", "gerber"],
      brand: "Gerber",
      productType: "Limited Edition",
      reviewCount: 8,
      ratingStars: { five: 6, four: 1, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card15',
      discount: 10,
      image: grocery3,
      title: "Heinz Banana Multigrain Cereal",
      description: "Delicious banana flavor with multigrains to help your baby grow strong and healthy.",
      additionalInfo: "Rich in Vitamin D, calcium and iron. Store in airtight container.",
      kg: 0.75,
      price: 32,
      value: 36,
      count: 1,
      category: "Breads & Bakery",
      life: new Date(),
      tags: ["heinz", "banana", "baby"],
      brand: "Heinz",
      productType: "Pre-order",
      reviewCount: 12,
      ratingStars: { five: 7, four: 2, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card16',
      discount: 20,
      image: grocery4,
      title: "Nestle Cerelac Rice & Milk",
      description: "Perfect starter cereal for babies beginning solid food journey. Made with rice and milk.",
      additionalInfo: "Recommended for 6+ months. Easy to digest and free from added preservatives.",
      kg: 1,
      price: 34,
      value: 42,
      count: 1,
      category: "Chips & Snacks",
      life: new Date(),
      tags: ["rice", "cerelac", "starter"],
      brand: "Nestle",
      productType: "Custom",
      reviewCount: 14,
      ratingStars: { five: 8, four: 3, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card17',
      discount: 5,
      image: grocery5,
      title: "Beech-Nut Multigrain Baby Cereal",
      description: "Organic multigrain cereal with no artificial ingredients. Simple and clean nutrition.",
      additionalInfo: "Certified organic. Gluten-free. Perfect for babies 6 months+.",
      kg: 0.6,
      price: 30,
      value: 32,
      count: 1,
      category: "Medical Healthcare",
      life: new Date(),
      tags: ["organic", "multigrain", "beech-nut"],
      brand: "Beech-Nut",
      productType: "Exclusive",
      reviewCount: 7,
      ratingStars: { five: 4, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card18',
      discount: 30,
      image: grocery6,
      title: "Happy Baby Organic Oats & Quinoa Cereal",
      description: "Blend of oats and quinoa for your baby’s healthy development. USDA organic certified.",
      additionalInfo: "Rich in iron and fiber. No artificial flavors or colors.",
      kg: 0.65,
      price: 26,
      value: 37,
      count: 1,
      category: "Frozen Foods",
      life: new Date(),
      tags: ["happybaby", "quinoa", "organic"],
      brand: "Happy Baby",
      productType: "Special Release",
      reviewCount: 9,
      ratingStars: { five: 6, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card19',
      discount: 18,
      image: grocery7,
      title: "Similac Go & Grow Toddler Food",
      description: "Toddler formula with DHA and iron to support growth and brain development.",
      additionalInfo: "Contains milk and soy. Use only as directed.",
      kg: 0.9,
      price: 38,
      value: 46,
      count: 1,
      category: "Grocery & Staples",
      life: new Date(),
      tags: ["similac", "toddler", "formula"],
      brand: "Similac",
      productType: "Limited Edition",
      reviewCount: 11,
      ratingStars: { five: 7, four: 2, three: 1, two: 1, one: 0 }
    },
    {
      id: 'card20',
      discount: 12,
      image: grocery8,
      title: "Earth’s Best Whole Grain Cereal",
      description: "Whole grain cereal made with organic ingredients. Easy on your baby’s tummy.",
      additionalInfo: "Non-GMO and iron-fortified. For babies 6 months+.",
      kg: 0.7,
      price: 29,
      value: 33,
      count: 1,
      category: "Vitamin Foods",
      life: new Date(),
      tags: ["earthsbest", "wholegrain", "organic"],
      brand: "Earth’s Best",
      productType: "Pre-order",
      reviewCount: 6,
      ratingStars: { five: 3, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card21',
      discount: 22,
      image: grocery9,
      title: "Nestum Infant Cereal Wheat & Honey",
      description: "Infant cereal with wheat and honey. A delicious, iron-rich food for babies.",
      additionalInfo: "Contains gluten and milk. Suitable for 8+ months.",
      kg: 1,
      price: 33,
      value: 42,
      count: 1,
      category: "Diet Foods",
      life: new Date(),
      tags: ["nestum", "wheat", "honey"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 13,
      ratingStars: { five: 6, four: 4, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card22',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Healthy Foods",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Cereal snack",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card23',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Vitamin Items",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Exclusive",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card24',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card25',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card26',
      discount: 15,
      image: grocery2,
      title: "Gerber Oatmeal Cereal for Babies",
      description: "Iron-fortified cereal to support brain development. Smooth texture for easy swallowing.",
      additionalInfo: "Non-GMO, single grain, and pediatrician recommended. Use within 30 days of opening.",
      kg: 0.5,
      price: 28,
      value: 33,
      count: 1,
      category: "Meats & Seafood",
      life: new Date(),
      tags: ["baby", "oatmeal", "gerber"],
      brand: "Gerber",
      productType: "Limited Edition",
      reviewCount: 8,
      ratingStars: { five: 6, four: 1, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card27',
      discount: 10,
      image: grocery3,
      title: "Heinz Banana Multigrain Cereal",
      description: "Delicious banana flavor with multigrains to help your baby grow strong and healthy.",
      additionalInfo: "Rich in Vitamin D, calcium and iron. Store in airtight container.",
      kg: 0.75,
      price: 32,
      value: 36,
      count: 1,
      category: "Breads & Bakery",
      life: new Date(),
      tags: ["heinz", "banana", "baby"],
      brand: "Heinz",
      productType: "Pre-order",
      reviewCount: 12,
      ratingStars: { five: 7, four: 2, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card28',
      discount: 20,
      image: grocery4,
      title: "Nestle Cerelac Rice & Milk",
      description: "Perfect starter cereal for babies beginning solid food journey. Made with rice and milk.",
      additionalInfo: "Recommended for 6+ months. Easy to digest and free from added preservatives.",
      kg: 1,
      price: 34,
      value: 42,
      count: 1,
      category: "Chips & Snacks",
      life: new Date(),
      tags: ["rice", "cerelac", "starter"],
      brand: "Nestle",
      productType: "Custom",
      reviewCount: 14,
      ratingStars: { five: 8, four: 3, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card29',
      discount: 5,
      image: grocery5,
      title: "Beech-Nut Multigrain Baby Cereal",
      description: "Organic multigrain cereal with no artificial ingredients. Simple and clean nutrition.",
      additionalInfo: "Certified organic. Gluten-free. Perfect for babies 6 months+.",
      kg: 0.6,
      price: 30,
      value: 32,
      count: 1,
      category: "Medical Healthcare",
      life: new Date(),
      tags: ["organic", "multigrain", "beech-nut"],
      brand: "Beech-Nut",
      productType: "Exclusive",
      reviewCount: 7,
      ratingStars: { five: 4, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card30',
      discount: 30,
      image: grocery6,
      title: "Happy Baby Organic Oats & Quinoa Cereal",
      description: "Blend of oats and quinoa for your baby’s healthy development. USDA organic certified.",
      additionalInfo: "Rich in iron and fiber. No artificial flavors or colors.",
      kg: 0.65,
      price: 26,
      value: 37,
      count: 1,
      category: "Frozen Foods",
      life: new Date(),
      tags: ["happybaby", "quinoa", "organic"],
      brand: "Happy Baby",
      productType: "Special Release",
      reviewCount: 9,
      ratingStars: { five: 6, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card31',
      discount: 18,
      image: grocery7,
      title: "Similac Go & Grow Toddler Food",
      description: "Toddler formula with DHA and iron to support growth and brain development.",
      additionalInfo: "Contains milk and soy. Use only as directed.",
      kg: 0.9,
      price: 38,
      value: 46,
      count: 1,
      category: "Grocery & Staples",
      life: new Date(),
      tags: ["similac", "toddler", "formula"],
      brand: "Similac",
      productType: "Limited Edition",
      reviewCount: 11,
      ratingStars: { five: 7, four: 2, three: 1, two: 1, one: 0 }
    },
    {
      id: 'card32',
      discount: 12,
      image: grocery8,
      title: "Earth’s Best Whole Grain Cereal",
      description: "Whole grain cereal made with organic ingredients. Easy on your baby’s tummy.",
      additionalInfo: "Non-GMO and iron-fortified. For babies 6 months+.",
      kg: 0.7,
      price: 29,
      value: 33,
      count: 1,
      category: "Vitamin Foods",
      life: new Date(),
      tags: ["earthsbest", "wholegrain", "organic"],
      brand: "Earth’s Best",
      productType: "Pre-order",
      reviewCount: 6,
      ratingStars: { five: 3, four: 2, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card33',
      discount: 22,
      image: grocery9,
      title: "Nestum Infant Cereal Wheat & Honey",
      description: "Infant cereal with wheat and honey. A delicious, iron-rich food for babies.",
      additionalInfo: "Contains gluten and milk. Suitable for 8+ months.",
      kg: 1,
      price: 33,
      value: 42,
      count: 1,
      category: "Diet Foods",
      life: new Date(),
      tags: ["nestum", "wheat", "honey"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 13,
      ratingStars: { five: 6, four: 4, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card34',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Healthy Foods",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Cereal snack",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card35',
      discount: 16,
      image: grocery10,
      title: "Plum Organics Super Puffs Cereal Snack",
      description: "Tasty cereal snack for toddlers made from organic fruits and veggies.",
      additionalInfo: "No added sugar. Great finger food for developing motor skills.",
      kg: 0.3,
      price: 24,
      value: 29,
      count: 1,
      category: "Vitamin Items",
      life: new Date(),
      tags: ["plum", "snacks", "organic"],
      brand: "Pre-order",
      productType: "Exclusive",
      reviewCount: 9,
      ratingStars: { five: 5, four: 3, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card36',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card37',
      discount: 25,
      image: grocery1,
      title: "Nestle Cerelac Mixed Fruits & Wheat with Milk",
      description: "Nutritious cereal for babies enriched with vitamins and minerals. Easy to digest and perfect for growing babies.",
      additionalInfo: "Store in a cool, dry place. Use within 4 weeks of opening. Suitable for babies aged 6 months and above.",
      kg: 1,
      price: 36,
      value: 45,
      count: 1,
      category: "Breakfast & Dairy",
      life: new Date(),
      tags: ["baby", "cereal", "nutrition"],
      brand: "Nestle",
      productType: "Original",
      reviewCount: 10,
      ratingStars: { five: 5, four: 2, three: 4, two: 1, one: 4 }
    },
    {
      id: 'card38',
      discount: 15,
      image: grocery2,
      title: "Gerber Oatmeal Cereal for Babies",
      description: "Iron-fortified cereal to support brain development. Smooth texture for easy swallowing.",
      additionalInfo: "Non-GMO, single grain, and pediatrician recommended. Use within 30 days of opening.",
      kg: 0.5,
      price: 28,
      value: 33,
      count: 1,
      category: "Meats & Seafood",
      life: new Date(),
      tags: ["baby", "oatmeal", "gerber"],
      brand: "Gerber",
      productType: "Limited Edition",
      reviewCount: 8,
      ratingStars: { five: 6, four: 1, three: 1, two: 0, one: 0 }
    },
    {
      id: 'card39',
      discount: 10,
      image: grocery3,
      title: "Heinz Banana Multigrain Cereal",
      description: "Delicious banana flavor with multigrains to help your baby grow strong and healthy.",
      additionalInfo: "Rich in Vitamin D, calcium and iron. Store in airtight container.",
      kg: 0.75,
      price: 32,
      value: 36,
      count: 1,
      category: "Breads & Bakery",
      life: new Date(),
      tags: ["heinz", "banana", "baby"],
      brand: "Heinz",
      productType: "Pre-order",
      reviewCount: 12,
      ratingStars: { five: 7, four: 2, three: 2, two: 1, one: 0 }
    },
    {
      id: 'card40',
      discount: 20,
      image: grocery4,
      title: "Nestle Cerelac Rice & Milk",
      description: "Perfect starter cereal for babies beginning solid food journey. Made with rice and milk.",
      additionalInfo: "Recommended for 6+ months. Easy to digest and free from added preservatives.",
      kg: 1,
      price: 34,
      value: 42,
      count: 1,
      category: "Chips & Snacks",
      life: new Date(),
      tags: ["rice", "cerelac", "starter"],
      brand: "Nestle",
      productType: "Custom",
      reviewCount: 14,
      ratingStars: { five: 8, four: 3, three: 2, two: 1, one: 0 }
    }
];  

export const settings = {
    dots: true,
    infinite: true,
    speed: 500,
    autoplay: true,
    slidesToShow: 5,
    slidesToScroll: 1,
    responsive: [
        {
          breakpoint: 1250,
          settings: {
            slidesToShow: 4,
            slidesToScroll: 1,
            infinite: true,
            dots: false
          }
        },
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 1,
            infinite: true,
            dots: false
          }
        },
        {
          breakpoint: 800,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 1,
            infinite: true,
            dots: false
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 1,
            infinite: true,
            slidesToScroll: 1,
          }
        },
      ]
};